name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install functions packages
        run: npm install
        working-directory: functions

      - name: install tests packages
        run: npm install
        working-directory: tests

      - name: install firebase tools
        run: npm install -g firebase-tools

      - name: run tests
        run: npm test
        working-directory: tests


  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: install functions packages
      run: npm install
      working-directory: functions

    - uses: actions/cache@v3
      name: Check if Playwright browser is cached
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-1.28.1

    - name: Install dependencies
      run: npm ci
      working-directory: e2e

    - name: Install Playwright browser if not cached
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps
      working-directory: e2e

    - name: Run Playwright tests
      run: npx playwright test
      working-directory: e2e

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  deploy:
    needs: [unit, e2e]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIREBASE_TEAMS_JOJO }}'
          channelId: live
          projectId: firebase-teams-jojo
