name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install tests packages
        run: cd tests; npm install

      - name: install firebase tools
        run: npm install -g firebase-tools

      - name: run tests
        run: cd tests; npm test

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIREBASE_TEAMS_JOJO }}'
          channelId: live
          projectId: firebase-teams-jojo
